// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: proto/tyto.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Tyto_StreamEvents_FullMethodName = "/tyto.Tyto/StreamEvents"
	Tyto_GetStats_FullMethodName     = "/tyto.Tyto/GetStats"
)

// TytoClient is the client API for Tyto service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TytoClient interface {
	StreamEvents(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TytoEvent], error)
	GetStats(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*StatsResponse, error)
}

type tytoClient struct {
	cc grpc.ClientConnInterface
}

func NewTytoClient(cc grpc.ClientConnInterface) TytoClient {
	return &tytoClient{cc}
}

func (c *tytoClient) StreamEvents(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TytoEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Tyto_ServiceDesc.Streams[0], Tyto_StreamEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[emptypb.Empty, TytoEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Tyto_StreamEventsClient = grpc.ServerStreamingClient[TytoEvent]

func (c *tytoClient) GetStats(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*StatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatsResponse)
	err := c.cc.Invoke(ctx, Tyto_GetStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TytoServer is the server API for Tyto service.
// All implementations must embed UnimplementedTytoServer
// for forward compatibility.
type TytoServer interface {
	StreamEvents(*emptypb.Empty, grpc.ServerStreamingServer[TytoEvent]) error
	GetStats(context.Context, *emptypb.Empty) (*StatsResponse, error)
	mustEmbedUnimplementedTytoServer()
}

// UnimplementedTytoServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTytoServer struct{}

func (UnimplementedTytoServer) StreamEvents(*emptypb.Empty, grpc.ServerStreamingServer[TytoEvent]) error {
	return status.Error(codes.Unimplemented, "method StreamEvents not implemented")
}
func (UnimplementedTytoServer) GetStats(context.Context, *emptypb.Empty) (*StatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStats not implemented")
}
func (UnimplementedTytoServer) mustEmbedUnimplementedTytoServer() {}
func (UnimplementedTytoServer) testEmbeddedByValue()              {}

// UnsafeTytoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TytoServer will
// result in compilation errors.
type UnsafeTytoServer interface {
	mustEmbedUnimplementedTytoServer()
}

func RegisterTytoServer(s grpc.ServiceRegistrar, srv TytoServer) {
	// If the following call panics, it indicates UnimplementedTytoServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Tyto_ServiceDesc, srv)
}

func _Tyto_StreamEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(emptypb.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TytoServer).StreamEvents(m, &grpc.GenericServerStream[emptypb.Empty, TytoEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Tyto_StreamEventsServer = grpc.ServerStreamingServer[TytoEvent]

func _Tyto_GetStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TytoServer).GetStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tyto_GetStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TytoServer).GetStats(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// Tyto_ServiceDesc is the grpc.ServiceDesc for Tyto service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Tyto_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tyto.Tyto",
	HandlerType: (*TytoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStats",
			Handler:    _Tyto_GetStats_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamEvents",
			Handler:       _Tyto_StreamEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/tyto.proto",
}
