syntax = "proto3";
package tyto;
option go_package = "github.com/hariprasadd0/tyto/src/userspace/proto";
import "google/protobuf/empty.proto";

message TytoEvent {
 uint64 timestamp  = 1;
 uint32 src_ip     = 2;
 uint32 pkt_count  = 3;
 uint32 protocol   = 4;
 }

 message StatsResponse {
     uint64 total_packets   = 1;
     uint64 dropped_packets = 2;
     uint64 udp_dropped     = 3;
     uint64 syn_dropped     = 4;
     uint64 icmp_dropped    = 5;
 }
 message ListEntry {
     uint32 ip = 1;           // network byte order (matches BPF map)
     bool blocked = 2;       // 0 or 1 (for blocklist readability)
 }

 message ListRequest {
     uint32 ip = 1;
 }

 message ListResponse {
     bool found = 1;
     uint32 ip = 2;
     bool value = 3;
 }

 message AddToListRequest {
     uint32 ip = 1;
 }

 message AddToListResponse {
     bool success = 1;
     string message = 2;
 }

 message RemoveFromListRequest {
     uint32 ip = 1;
 }

 message RemoveFromListResponse {
     bool success = 1;
     string message = 2;
 }

 message ListAllResponse {
     repeated ListEntry entries = 1;
 }

 service Tyto {
     rpc StreamEvents(google.protobuf.Empty) returns (stream TytoEvent);
     rpc GetStats(google.protobuf.Empty) returns (StatsResponse);

     rpc AllowlistAdd(AddToListRequest) returns (AddToListResponse);
     rpc AllowlistRemove(RemoveFromListRequest) returns (RemoveFromListResponse);
     rpc AllowlistCheck(ListRequest) returns (ListResponse);
     rpc AllowlistListAll(google.protobuf.Empty) returns (ListAllResponse);

     rpc BlocklistAdd(AddToListRequest) returns (AddToListResponse);
     rpc BlocklistRemove(RemoveFromListRequest) returns (RemoveFromListResponse);
     rpc BlocklistCheck(ListRequest) returns (ListResponse);
     rpc BlocklistListAll(google.protobuf.Empty) returns (ListAllResponse);
 }
