// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/tyto.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TytoEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     uint64                 `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	SrcIp         uint32                 `protobuf:"varint,2,opt,name=src_ip,json=srcIp,proto3" json:"src_ip,omitempty"`
	PktCount      uint32                 `protobuf:"varint,3,opt,name=pkt_count,json=pktCount,proto3" json:"pkt_count,omitempty"`
	Protocol      uint32                 `protobuf:"varint,4,opt,name=protocol,proto3" json:"protocol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TytoEvent) Reset() {
	*x = TytoEvent{}
	mi := &file_proto_tyto_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TytoEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TytoEvent) ProtoMessage() {}

func (x *TytoEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tyto_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TytoEvent.ProtoReflect.Descriptor instead.
func (*TytoEvent) Descriptor() ([]byte, []int) {
	return file_proto_tyto_proto_rawDescGZIP(), []int{0}
}

func (x *TytoEvent) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *TytoEvent) GetSrcIp() uint32 {
	if x != nil {
		return x.SrcIp
	}
	return 0
}

func (x *TytoEvent) GetPktCount() uint32 {
	if x != nil {
		return x.PktCount
	}
	return 0
}

func (x *TytoEvent) GetProtocol() uint32 {
	if x != nil {
		return x.Protocol
	}
	return 0
}

type StatsResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TotalPackets   uint64                 `protobuf:"varint,1,opt,name=total_packets,json=totalPackets,proto3" json:"total_packets,omitempty"`
	DroppedPackets uint64                 `protobuf:"varint,2,opt,name=dropped_packets,json=droppedPackets,proto3" json:"dropped_packets,omitempty"`
	UdpDropped     uint64                 `protobuf:"varint,3,opt,name=udp_dropped,json=udpDropped,proto3" json:"udp_dropped,omitempty"`
	SynDropped     uint64                 `protobuf:"varint,4,opt,name=syn_dropped,json=synDropped,proto3" json:"syn_dropped,omitempty"`
	IcmpDropped    uint64                 `protobuf:"varint,5,opt,name=icmp_dropped,json=icmpDropped,proto3" json:"icmp_dropped,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StatsResponse) Reset() {
	*x = StatsResponse{}
	mi := &file_proto_tyto_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResponse) ProtoMessage() {}

func (x *StatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tyto_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsResponse.ProtoReflect.Descriptor instead.
func (*StatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_tyto_proto_rawDescGZIP(), []int{1}
}

func (x *StatsResponse) GetTotalPackets() uint64 {
	if x != nil {
		return x.TotalPackets
	}
	return 0
}

func (x *StatsResponse) GetDroppedPackets() uint64 {
	if x != nil {
		return x.DroppedPackets
	}
	return 0
}

func (x *StatsResponse) GetUdpDropped() uint64 {
	if x != nil {
		return x.UdpDropped
	}
	return 0
}

func (x *StatsResponse) GetSynDropped() uint64 {
	if x != nil {
		return x.SynDropped
	}
	return 0
}

func (x *StatsResponse) GetIcmpDropped() uint64 {
	if x != nil {
		return x.IcmpDropped
	}
	return 0
}

var File_proto_tyto_proto protoreflect.FileDescriptor

const file_proto_tyto_proto_rawDesc = "" +
	"\n" +
	"\x10proto/tyto.proto\x12\x04tyto\x1a\x1bgoogle/protobuf/empty.proto\"y\n" +
	"\tTytoEvent\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x04R\ttimestamp\x12\x15\n" +
	"\x06src_ip\x18\x02 \x01(\rR\x05srcIp\x12\x1b\n" +
	"\tpkt_count\x18\x03 \x01(\rR\bpktCount\x12\x1a\n" +
	"\bprotocol\x18\x04 \x01(\rR\bprotocol\"\xc2\x01\n" +
	"\rStatsResponse\x12#\n" +
	"\rtotal_packets\x18\x01 \x01(\x04R\ftotalPackets\x12'\n" +
	"\x0fdropped_packets\x18\x02 \x01(\x04R\x0edroppedPackets\x12\x1f\n" +
	"\vudp_dropped\x18\x03 \x01(\x04R\n" +
	"udpDropped\x12\x1f\n" +
	"\vsyn_dropped\x18\x04 \x01(\x04R\n" +
	"synDropped\x12!\n" +
	"\ficmp_dropped\x18\x05 \x01(\x04R\vicmpDropped2z\n" +
	"\x04Tyto\x129\n" +
	"\fStreamEvents\x12\x16.google.protobuf.Empty\x1a\x0f.tyto.TytoEvent0\x01\x127\n" +
	"\bGetStats\x12\x16.google.protobuf.Empty\x1a\x13.tyto.StatsResponseB2Z0github.com/hariprasadd0/tyto/src/userspace/protob\x06proto3"

var (
	file_proto_tyto_proto_rawDescOnce sync.Once
	file_proto_tyto_proto_rawDescData []byte
)

func file_proto_tyto_proto_rawDescGZIP() []byte {
	file_proto_tyto_proto_rawDescOnce.Do(func() {
		file_proto_tyto_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_tyto_proto_rawDesc), len(file_proto_tyto_proto_rawDesc)))
	})
	return file_proto_tyto_proto_rawDescData
}

var file_proto_tyto_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_tyto_proto_goTypes = []any{
	(*TytoEvent)(nil),     // 0: tyto.TytoEvent
	(*StatsResponse)(nil), // 1: tyto.StatsResponse
	(*emptypb.Empty)(nil), // 2: google.protobuf.Empty
}
var file_proto_tyto_proto_depIdxs = []int32{
	2, // 0: tyto.Tyto.StreamEvents:input_type -> google.protobuf.Empty
	2, // 1: tyto.Tyto.GetStats:input_type -> google.protobuf.Empty
	0, // 2: tyto.Tyto.StreamEvents:output_type -> tyto.TytoEvent
	1, // 3: tyto.Tyto.GetStats:output_type -> tyto.StatsResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_tyto_proto_init() }
func file_proto_tyto_proto_init() {
	if File_proto_tyto_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_tyto_proto_rawDesc), len(file_proto_tyto_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_tyto_proto_goTypes,
		DependencyIndexes: file_proto_tyto_proto_depIdxs,
		MessageInfos:      file_proto_tyto_proto_msgTypes,
	}.Build()
	File_proto_tyto_proto = out.File
	file_proto_tyto_proto_goTypes = nil
	file_proto_tyto_proto_depIdxs = nil
}
