// Code generated by bpf2go; DO NOT EDIT.
//go:build (386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm) && linux

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type tytoIpEntry struct {
	_           structs.HostLayout
	WindowStart uint64
	PktCount    uint32
	Blocked     uint32
}

type tytoTytoStats struct {
	_              structs.HostLayout
	TotalPackets   uint64
	PassedPackets  uint64
	DroppedPackets uint64
	UdpPackets     uint64
	SynPackets     uint64
	IcmpPackets    uint64
	UdpDropped     uint64
	SynDropped     uint64
	IcmpDropped    uint64
}

// loadTyto returns the embedded CollectionSpec for tyto.
func loadTyto() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_TytoBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load tyto: %w", err)
	}

	return spec, err
}

// loadTytoObjects loads tyto and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*tytoObjects
//	*tytoPrograms
//	*tytoMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadTytoObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadTyto()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// tytoSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tytoSpecs struct {
	tytoProgramSpecs
	tytoMapSpecs
	tytoVariableSpecs
}

// tytoProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tytoProgramSpecs struct {
	XdpProg *ebpf.ProgramSpec `ebpf:"xdp_prog"`
}

// tytoMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tytoMapSpecs struct {
	AllowlistMap *ebpf.MapSpec `ebpf:"allowlist_map"`
	BlocklistMap *ebpf.MapSpec `ebpf:"blocklist_map"`
	Events       *ebpf.MapSpec `ebpf:"events"`
	IcmpTrackMap *ebpf.MapSpec `ebpf:"icmp_track_map"`
	StatsMap     *ebpf.MapSpec `ebpf:"stats_map"`
	SynTrackMap  *ebpf.MapSpec `ebpf:"syn_track_map"`
	UdpTrackMap  *ebpf.MapSpec `ebpf:"udp_track_map"`
}

// tytoVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tytoVariableSpecs struct {
}

// tytoObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadTytoObjects or ebpf.CollectionSpec.LoadAndAssign.
type tytoObjects struct {
	tytoPrograms
	tytoMaps
	tytoVariables
}

func (o *tytoObjects) Close() error {
	return _TytoClose(
		&o.tytoPrograms,
		&o.tytoMaps,
	)
}

// tytoMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadTytoObjects or ebpf.CollectionSpec.LoadAndAssign.
type tytoMaps struct {
	AllowlistMap *ebpf.Map `ebpf:"allowlist_map"`
	BlocklistMap *ebpf.Map `ebpf:"blocklist_map"`
	Events       *ebpf.Map `ebpf:"events"`
	IcmpTrackMap *ebpf.Map `ebpf:"icmp_track_map"`
	StatsMap     *ebpf.Map `ebpf:"stats_map"`
	SynTrackMap  *ebpf.Map `ebpf:"syn_track_map"`
	UdpTrackMap  *ebpf.Map `ebpf:"udp_track_map"`
}

func (m *tytoMaps) Close() error {
	return _TytoClose(
		m.AllowlistMap,
		m.BlocklistMap,
		m.Events,
		m.IcmpTrackMap,
		m.StatsMap,
		m.SynTrackMap,
		m.UdpTrackMap,
	)
}

// tytoVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadTytoObjects or ebpf.CollectionSpec.LoadAndAssign.
type tytoVariables struct {
}

// tytoPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadTytoObjects or ebpf.CollectionSpec.LoadAndAssign.
type tytoPrograms struct {
	XdpProg *ebpf.Program `ebpf:"xdp_prog"`
}

func (p *tytoPrograms) Close() error {
	return _TytoClose(
		p.XdpProg,
	)
}

func _TytoClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed tyto_bpfel.o
var _TytoBytes []byte
